### ISSUE TITLE
Problem with the design of home page

### ISSUE THREAD

**Issue by sfazliddin** [Smqkmj/Group-Project#1]
the navbar is conflicting in the main page

**Comment by lynettelhh** [comment]
maybe try to include the bootstrap css and see 
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

**Comment by sfazliddin** [comment]
NavBar is looking good
